### ISSUE TITLE
rmapy.is_auth() is False even immediately after registering the device - Config not persistent?

### ISSUE THREAD

**Issue by micheledicosmo** [subutux/rmapy#12] opened 2021-01-28 22:09 UTC
```
rmapy = Client()                                                                                                                                             rmapy.register_device("ktgglqyq")
rmapy.renew_token()
```

The above code succeeds (API returns 200).

However, when I then do `rmapy.is_auth()` return `False` immediately after.

**Comment by micheledicosmo** [comment] 2021-01-28 22:12
I noticed that the config is also not persistent: this might be the problem (i.e. the token is lost when I run the script again)

**Comment by subutux** [comment] 2021-01-30 13:43
Hmm that’s strange. So no Config file is present @ `$HOME/.rmapi`?

Did you register your device first?

**Comment by micheledicosmo** [comment] 2021-01-30 14:41
Ta. `devicetoken` is set, but `usertoken` is empty.

**Comment by subutux** [comment] 2021-01-30 17:18
Hi,

I've just tested this, starting from scratch, with no `$HOME/.rmapi` file present.
```
In [5]: from rmapy.api import Client

In [6]: rmapy = Client()

In [7]: rmapy.is_auth()
Out[7]: False

In [8]: rmapy.register_device("akrxbsyw")
Out[8]: True

In [9]: rmapy.is_auth()
Out[9]: False

In [10]: rmapy.renew_token()
Out[10]: True

In [11]: rmapy.is_auth()
Out[11]: True
```
and my `$HOME/.rmapi` now contains **both** the `devicetoken` and `usertoken`.
is your `$HOME/.rmapi` writable?

Could you try to remove your `$HOME/.rmapi` file and register again?

**Comment by micheledicosmo** [comment] 2021-01-30 18:00
Still no luck by deleting the file and redoing: same behaviour. Are both token set by `rmapy` as part of the same operation?

**Comment by subutux** [comment] 2021-01-30 20:41
* The `devicetoken` is set by `rmapy.api.Client.register_device()`,
* `usertoken` by `rmapy.api.Client.renew_token()`.

Which version are you using?

**Comment by subutux** [comment] 2021-02-15 10:28
I'm closing this issue because I cannot reproduce it.

**Closed by subutux** 2021-02-15 10:28 UTC
